### ISSUE TITLE
[Feature request] Add suport for select an array of database names for backup only

### ISSUE THREAD

**Issue by ZeusAFK** [axllent/phpmybackup#4]
How I can do for only backup 1 database without adding new databases to ignoreDatabases array everytime I create a new database?.

**Comment by axllent** [comment]
This is a good idea! I intend to rewrite the entire class in the (hopefully) near future (pdo or mysqli) and will look at implementing this option.

**Comment by axllent** [comment]
I've just finished rewriting the script which now requires mysqli support, and now also supports `$db->includeDatabases = ['i-only-want-this-db', 'also-this-one'];` so you should be able to specify which databases you wish to back up.

Please note that due to a change in the local cache file naming, all (configured) tables will initially be downloaded again. This was due to the original script not picking up table CREATE changes (eg: if a field length was changed, but the data remained the same).
