### ISSUE TITLE
just a qucik question, 

### ISSUE THREAD

**Issue by kezenwa** [axllent/phpmybackup#5]
what class method handles the **Differential**  backUp portion ?

The class methods don't have comments hence difficult for one to easily make modifications.

What exactly does the method syncTables() do ?

Am I right to say the method rotateFiles() is responsible for dong the **DIFFERENCIAL** magic

**Comment by axllent** [comment]
Hi @kezenwa . You're absolutely right, the code isn't commented which is why it took me 5 minutes to work it out myself (keeping in mind that I wrote this several years ago, and it has long been replaced by something else since) :)

In `syncTables()` there is this: https://github.com/axllent/phpmybackup/blob/3c3aa4ffa90fe444ab4b4ad603d50d5f4bea7fa9/phpmybackup.php#L241-L244 which is where the incremental part is. Basically it creates a table checksum before it downloads each table, and if the file already exists it doesn't download the table again.  This way only tables with modified data are downloaded.

**Comment by kezenwa** [comment]
> 

Thanks for your timely response.

I intends using this since it's based on PHP. Would use it as starting block as I intends adding INCREMENTAL backUp to it.
